//  Given two strings s and t which consist of only lowercase letters.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Find the letter that was added in t.
#include <iostream>
#include <string>
using namespace std;
char findTheDifference(string s, string t)
{
    int A[26] = {};
    int i = 0;
    while (s[i] != '\0')
    {
        A[s[i] - 97]++;
        i++;
    }

    i = 0;
    int B[26] = {};
    while (t[i] != '\0')
    {
        B[t[i] - 97]++;
        i++;
    }
    for (int i = 0; i < 26; i++)
    {
        if (A[i] != B[i])
            return (i + 97);
    }
    return '\0';
}
int main()
{
    string s, t;
    s = "chakkres";
    t = "kkkrasech";
    cout << findTheDifference(s, t);
}